export { default as Main } from './layout/Main'
export { default as Auth } from './layout/Auth'
export { default as Book } from './layout/Book'
export { default as Order } from './layout/Order'
export { default as Basket } from './layout/Basket'
export { default as Header } from './common/Header'